VAGRANTFILE_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #操作系统镜像
  config.vm.box = 'bento/centos-8'
  #虚拟机主机名
  config.vm.hostname = 'master'
  config.ssh.insert_key = false
  #操作系统初始化脚本
  config.vm.provision :shell, path: 'master-script.sh'
  #配置网络 IP 地址
  config.vm.network :private_network, ip: '192.168.50.10'
  #配置和物理机连接的网络端口
  config.vm.network 'forwarded_port', guest: 80, host: 80
  config.vm.network 'forwarded_port', guest: 9200, host: 9200
  config.vm.network 'forwarded_port', guest: 5601, host: 5601
  #设置虚拟机的内存为 4GB
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '4096']
  end
end

#    (1..N).each do |i|
#        config.vm.provider "virtualbox" do |v|
#          v.memory = 1024
#          v.cpus = 1
#        end
#        config.vm.define "node-#{i}" do |node|
#            node.vm.box = IMAGE_NAME
#            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
#            node.vm.hostname = "node-#{i}"
#            node.vm.provision "shell", path: "beats-script.sh"
#        end
#    end
