# -*- mode: ruby -*-
# vi: set ft=ruby :
IMAGE_NAME = 'bento/centos-8'

Vagrant.configure("2") do |config|
  config.vm.define "master1" do |master1|
    config.vm.box = IMAGE_NAME    #操作系统镜像
    config.ssh.insert_key = false
    config.vm.hostname = 'master-1'  #主机名
    config.vm.network :private_network, ip: "192.168.50.10"  #私有网络 Ip 地址
    config.vm.network 'forwarded_port', guest: 9200, host: 9200
    config.vm.network 'forwarded_port', guest: 5601, host: 5601
    config.vm.provision :shell, path: 'pre-install-EK.sh' #操作系统初始化脚本
    config.vm.provider :virtualbox do |vb|
      vb.memory = 4096 #内存
      vb.cpus = 2 #CPU 数
    end
  end
end